// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkwsgecgfiwpkkawnhyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrd3NnZWNnZml3cGtrYXduaHlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODYwODksImV4cCI6MjA2NzU2MjA4OX0.KyXtQyKE1cLutsTt3CHkSWtaFh2UszQ9_0oRhCEv92k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});